apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: narwhal-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:e48466f3e7925ef2cf68f1c4a38ba98fcdb90f0f@sha256:5dc8848853a09f96c0a7c472a574755a0e0d9d3eebdaf88f40894ff50f4002a9
          name: container-image
